// Code generated by mockery. DO NOT EDIT.

package orm

import (
	orm "github.com/goravel/framework/contracts/database/orm"
	mock "github.com/stretchr/testify/mock"
)

// ModelWithThroughRelations is an autogenerated mock type for the ModelWithThroughRelations type
type ModelWithThroughRelations struct {
	mock.Mock
}

type ModelWithThroughRelations_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelWithThroughRelations) EXPECT() *ModelWithThroughRelations_Expecter {
	return &ModelWithThroughRelations_Expecter{mock: &_m.Mock}
}

// ThroughRelations provides a mock function with no fields
func (_m *ModelWithThroughRelations) ThroughRelations() map[string]orm.ThroughRelation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ThroughRelations")
	}

	var r0 map[string]orm.ThroughRelation
	if rf, ok := ret.Get(0).(func() map[string]orm.ThroughRelation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]orm.ThroughRelation)
		}
	}

	return r0
}

// ModelWithThroughRelations_ThroughRelations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ThroughRelations'
type ModelWithThroughRelations_ThroughRelations_Call struct {
	*mock.Call
}

// ThroughRelations is a helper method to define mock.On call
func (_e *ModelWithThroughRelations_Expecter) ThroughRelations() *ModelWithThroughRelations_ThroughRelations_Call {
	return &ModelWithThroughRelations_ThroughRelations_Call{Call: _e.mock.On("ThroughRelations")}
}

func (_c *ModelWithThroughRelations_ThroughRelations_Call) Run(run func()) *ModelWithThroughRelations_ThroughRelations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelWithThroughRelations_ThroughRelations_Call) Return(_a0 map[string]orm.ThroughRelation) *ModelWithThroughRelations_ThroughRelations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ModelWithThroughRelations_ThroughRelations_Call) RunAndReturn(run func() map[string]orm.ThroughRelation) *ModelWithThroughRelations_ThroughRelations_Call {
	_c.Call.Return(run)
	return _c
}

// NewModelWithThroughRelations creates a new instance of ModelWithThroughRelations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelWithThroughRelations(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelWithThroughRelations {
	mock := &ModelWithThroughRelations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
