// Code generated by mockery. DO NOT EDIT.

package orm

import (
	orm "github.com/goravel/framework/contracts/database/orm"
	mock "github.com/stretchr/testify/mock"
)

// ModelWithMorphRelations is an autogenerated mock type for the ModelWithMorphRelations type
type ModelWithMorphRelations struct {
	mock.Mock
}

type ModelWithMorphRelations_Expecter struct {
	mock *mock.Mock
}

func (_m *ModelWithMorphRelations) EXPECT() *ModelWithMorphRelations_Expecter {
	return &ModelWithMorphRelations_Expecter{mock: &_m.Mock}
}

// MorphRelations provides a mock function with no fields
func (_m *ModelWithMorphRelations) MorphRelations() map[string]orm.MorphRelation {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for MorphRelations")
	}

	var r0 map[string]orm.MorphRelation
	if rf, ok := ret.Get(0).(func() map[string]orm.MorphRelation); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]orm.MorphRelation)
		}
	}

	return r0
}

// ModelWithMorphRelations_MorphRelations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MorphRelations'
type ModelWithMorphRelations_MorphRelations_Call struct {
	*mock.Call
}

// MorphRelations is a helper method to define mock.On call
func (_e *ModelWithMorphRelations_Expecter) MorphRelations() *ModelWithMorphRelations_MorphRelations_Call {
	return &ModelWithMorphRelations_MorphRelations_Call{Call: _e.mock.On("MorphRelations")}
}

func (_c *ModelWithMorphRelations_MorphRelations_Call) Run(run func()) *ModelWithMorphRelations_MorphRelations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ModelWithMorphRelations_MorphRelations_Call) Return(_a0 map[string]orm.MorphRelation) *ModelWithMorphRelations_MorphRelations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ModelWithMorphRelations_MorphRelations_Call) RunAndReturn(run func() map[string]orm.MorphRelation) *ModelWithMorphRelations_MorphRelations_Call {
	_c.Call.Return(run)
	return _c
}

// NewModelWithMorphRelations creates a new instance of ModelWithMorphRelations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewModelWithMorphRelations(t interface {
	mock.TestingT
	Cleanup(func())
}) *ModelWithMorphRelations {
	mock := &ModelWithMorphRelations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
