// Code generated by mockery. DO NOT EDIT.

package orm

import (
	context "context"

	database "github.com/goravel/framework/contracts/database"
	db "github.com/goravel/framework/contracts/database/db"

	mock "github.com/stretchr/testify/mock"

	orm "github.com/goravel/framework/contracts/database/orm"

	sql "database/sql"
)

// Orm is an autogenerated mock type for the Orm type
type Orm struct {
	mock.Mock
}

type Orm_Expecter struct {
	mock *mock.Mock
}

func (_m *Orm) EXPECT() *Orm_Expecter {
	return &Orm_Expecter{mock: &_m.Mock}
}

// Associate provides a mock function with given fields: parent, relation, owner
func (_m *Orm) Associate(parent interface{}, relation string, owner interface{}) error {
	ret := _m.Called(parent, relation, owner)

	if len(ret) == 0 {
		panic("no return value specified for Associate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}) error); ok {
		r0 = rf(parent, relation, owner)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_Associate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Associate'
type Orm_Associate_Call struct {
	*mock.Call
}

// Associate is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - owner interface{}
func (_e *Orm_Expecter) Associate(parent interface{}, relation interface{}, owner interface{}) *Orm_Associate_Call {
	return &Orm_Associate_Call{Call: _e.mock.On("Associate", parent, relation, owner)}
}

func (_c *Orm_Associate_Call) Run(run func(parent interface{}, relation string, owner interface{})) *Orm_Associate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Orm_Associate_Call) Return(_a0 error) *Orm_Associate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Associate_Call) RunAndReturn(run func(interface{}, string, interface{}) error) *Orm_Associate_Call {
	_c.Call.Return(run)
	return _c
}

// Attach provides a mock function with given fields: parent, relation, ids
func (_m *Orm) Attach(parent interface{}, relation string, ids []interface{}) error {
	ret := _m.Called(parent, relation, ids)

	if len(ret) == 0 {
		panic("no return value specified for Attach")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, []interface{}) error); ok {
		r0 = rf(parent, relation, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_Attach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Attach'
type Orm_Attach_Call struct {
	*mock.Call
}

// Attach is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - ids []interface{}
func (_e *Orm_Expecter) Attach(parent interface{}, relation interface{}, ids interface{}) *Orm_Attach_Call {
	return &Orm_Attach_Call{Call: _e.mock.On("Attach", parent, relation, ids)}
}

func (_c *Orm_Attach_Call) Run(run func(parent interface{}, relation string, ids []interface{})) *Orm_Attach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].([]interface{}))
	})
	return _c
}

func (_c *Orm_Attach_Call) Return(_a0 error) *Orm_Attach_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Attach_Call) RunAndReturn(run func(interface{}, string, []interface{}) error) *Orm_Attach_Call {
	_c.Call.Return(run)
	return _c
}

// AttachWithPivot provides a mock function with given fields: parent, relation, idsWithAttrs
func (_m *Orm) AttachWithPivot(parent interface{}, relation string, idsWithAttrs map[interface{}]map[string]interface{}) error {
	ret := _m.Called(parent, relation, idsWithAttrs)

	if len(ret) == 0 {
		panic("no return value specified for AttachWithPivot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, map[interface{}]map[string]interface{}) error); ok {
		r0 = rf(parent, relation, idsWithAttrs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_AttachWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachWithPivot'
type Orm_AttachWithPivot_Call struct {
	*mock.Call
}

// AttachWithPivot is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - idsWithAttrs map[interface{}]map[string]interface{}
func (_e *Orm_Expecter) AttachWithPivot(parent interface{}, relation interface{}, idsWithAttrs interface{}) *Orm_AttachWithPivot_Call {
	return &Orm_AttachWithPivot_Call{Call: _e.mock.On("AttachWithPivot", parent, relation, idsWithAttrs)}
}

func (_c *Orm_AttachWithPivot_Call) Run(run func(parent interface{}, relation string, idsWithAttrs map[interface{}]map[string]interface{})) *Orm_AttachWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(map[interface{}]map[string]interface{}))
	})
	return _c
}

func (_c *Orm_AttachWithPivot_Call) Return(_a0 error) *Orm_AttachWithPivot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_AttachWithPivot_Call) RunAndReturn(run func(interface{}, string, map[interface{}]map[string]interface{}) error) *Orm_AttachWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function with no fields
func (_m *Orm) Config() database.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 database.Config
	if rf, ok := ret.Get(0).(func() database.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(database.Config)
	}

	return r0
}

// Orm_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type Orm_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *Orm_Expecter) Config() *Orm_Config_Call {
	return &Orm_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *Orm_Config_Call) Run(run func()) *Orm_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Orm_Config_Call) Return(_a0 database.Config) *Orm_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Config_Call) RunAndReturn(run func() database.Config) *Orm_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Connection provides a mock function with given fields: name
func (_m *Orm) Connection(name string) orm.Orm {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Connection")
	}

	var r0 orm.Orm
	if rf, ok := ret.Get(0).(func(string) orm.Orm); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Orm)
		}
	}

	return r0
}

// Orm_Connection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connection'
type Orm_Connection_Call struct {
	*mock.Call
}

// Connection is a helper method to define mock.On call
//   - name string
func (_e *Orm_Expecter) Connection(name interface{}) *Orm_Connection_Call {
	return &Orm_Connection_Call{Call: _e.mock.On("Connection", name)}
}

func (_c *Orm_Connection_Call) Run(run func(name string)) *Orm_Connection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Orm_Connection_Call) Return(_a0 orm.Orm) *Orm_Connection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Connection_Call) RunAndReturn(run func(string) orm.Orm) *Orm_Connection_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: parent, relation, dest
func (_m *Orm) Create(parent interface{}, relation string, dest interface{}) error {
	ret := _m.Called(parent, relation, dest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}) error); ok {
		r0 = rf(parent, relation, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Orm_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - dest interface{}
func (_e *Orm_Expecter) Create(parent interface{}, relation interface{}, dest interface{}) *Orm_Create_Call {
	return &Orm_Create_Call{Call: _e.mock.On("Create", parent, relation, dest)}
}

func (_c *Orm_Create_Call) Run(run func(parent interface{}, relation string, dest interface{})) *Orm_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Orm_Create_Call) Return(_a0 error) *Orm_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Create_Call) RunAndReturn(run func(interface{}, string, interface{}) error) *Orm_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMany provides a mock function with given fields: parent, relation, dests
func (_m *Orm) CreateMany(parent interface{}, relation string, dests interface{}) error {
	ret := _m.Called(parent, relation, dests)

	if len(ret) == 0 {
		panic("no return value specified for CreateMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}) error); ok {
		r0 = rf(parent, relation, dests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_CreateMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMany'
type Orm_CreateMany_Call struct {
	*mock.Call
}

// CreateMany is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - dests interface{}
func (_e *Orm_Expecter) CreateMany(parent interface{}, relation interface{}, dests interface{}) *Orm_CreateMany_Call {
	return &Orm_CreateMany_Call{Call: _e.mock.On("CreateMany", parent, relation, dests)}
}

func (_c *Orm_CreateMany_Call) Run(run func(parent interface{}, relation string, dests interface{})) *Orm_CreateMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Orm_CreateMany_Call) Return(_a0 error) *Orm_CreateMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_CreateMany_Call) RunAndReturn(run func(interface{}, string, interface{}) error) *Orm_CreateMany_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function with no fields
func (_m *Orm) DB() (*sql.DB, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *sql.DB
	var r1 error
	if rf, ok := ret.Get(0).(func() (*sql.DB, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orm_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type Orm_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *Orm_Expecter) DB() *Orm_DB_Call {
	return &Orm_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *Orm_DB_Call) Run(run func()) *Orm_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Orm_DB_Call) Return(_a0 *sql.DB, _a1 error) *Orm_DB_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orm_DB_Call) RunAndReturn(run func() (*sql.DB, error)) *Orm_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DatabaseName provides a mock function with no fields
func (_m *Orm) DatabaseName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DatabaseName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Orm_DatabaseName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DatabaseName'
type Orm_DatabaseName_Call struct {
	*mock.Call
}

// DatabaseName is a helper method to define mock.On call
func (_e *Orm_Expecter) DatabaseName() *Orm_DatabaseName_Call {
	return &Orm_DatabaseName_Call{Call: _e.mock.On("DatabaseName")}
}

func (_c *Orm_DatabaseName_Call) Run(run func()) *Orm_DatabaseName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Orm_DatabaseName_Call) Return(_a0 string) *Orm_DatabaseName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_DatabaseName_Call) RunAndReturn(run func() string) *Orm_DatabaseName_Call {
	_c.Call.Return(run)
	return _c
}

// Detach provides a mock function with given fields: parent, relation, ids
func (_m *Orm) Detach(parent interface{}, relation string, ids ...interface{}) (int64, error) {
	var _ca []interface{}
	_ca = append(_ca, parent, relation)
	_ca = append(_ca, ids...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Detach")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, string, ...interface{}) (int64, error)); ok {
		return rf(parent, relation, ids...)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, ...interface{}) int64); ok {
		r0 = rf(parent, relation, ids...)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, ...interface{}) error); ok {
		r1 = rf(parent, relation, ids...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orm_Detach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Detach'
type Orm_Detach_Call struct {
	*mock.Call
}

// Detach is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - ids ...interface{}
func (_e *Orm_Expecter) Detach(parent interface{}, relation interface{}, ids ...interface{}) *Orm_Detach_Call {
	return &Orm_Detach_Call{Call: _e.mock.On("Detach",
		append([]interface{}{parent, relation}, ids...)...)}
}

func (_c *Orm_Detach_Call) Run(run func(parent interface{}, relation string, ids ...interface{})) *Orm_Detach_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *Orm_Detach_Call) Return(_a0 int64, _a1 error) *Orm_Detach_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orm_Detach_Call) RunAndReturn(run func(interface{}, string, ...interface{}) (int64, error)) *Orm_Detach_Call {
	_c.Call.Return(run)
	return _c
}

// Dissociate provides a mock function with given fields: parent, relation
func (_m *Orm) Dissociate(parent interface{}, relation string) error {
	ret := _m.Called(parent, relation)

	if len(ret) == 0 {
		panic("no return value specified for Dissociate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string) error); ok {
		r0 = rf(parent, relation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_Dissociate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dissociate'
type Orm_Dissociate_Call struct {
	*mock.Call
}

// Dissociate is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
func (_e *Orm_Expecter) Dissociate(parent interface{}, relation interface{}) *Orm_Dissociate_Call {
	return &Orm_Dissociate_Call{Call: _e.mock.On("Dissociate", parent, relation)}
}

func (_c *Orm_Dissociate_Call) Run(run func(parent interface{}, relation string)) *Orm_Dissociate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string))
	})
	return _c
}

func (_c *Orm_Dissociate_Call) Return(_a0 error) *Orm_Dissociate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Dissociate_Call) RunAndReturn(run func(interface{}, string) error) *Orm_Dissociate_Call {
	_c.Call.Return(run)
	return _c
}

// Factory provides a mock function with no fields
func (_m *Orm) Factory() orm.Factory {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Factory")
	}

	var r0 orm.Factory
	if rf, ok := ret.Get(0).(func() orm.Factory); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Factory)
		}
	}

	return r0
}

// Orm_Factory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Factory'
type Orm_Factory_Call struct {
	*mock.Call
}

// Factory is a helper method to define mock.On call
func (_e *Orm_Expecter) Factory() *Orm_Factory_Call {
	return &Orm_Factory_Call{Call: _e.mock.On("Factory")}
}

func (_c *Orm_Factory_Call) Run(run func()) *Orm_Factory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Orm_Factory_Call) Return(_a0 orm.Factory) *Orm_Factory_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Factory_Call) RunAndReturn(run func() orm.Factory) *Orm_Factory_Call {
	_c.Call.Return(run)
	return _c
}

// FindOrNew provides a mock function with given fields: parent, relation, id, dest
func (_m *Orm) FindOrNew(parent interface{}, relation string, id interface{}, dest interface{}) error {
	ret := _m.Called(parent, relation, id, dest)

	if len(ret) == 0 {
		panic("no return value specified for FindOrNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}, interface{}) error); ok {
		r0 = rf(parent, relation, id, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_FindOrNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOrNew'
type Orm_FindOrNew_Call struct {
	*mock.Call
}

// FindOrNew is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - id interface{}
//   - dest interface{}
func (_e *Orm_Expecter) FindOrNew(parent interface{}, relation interface{}, id interface{}, dest interface{}) *Orm_FindOrNew_Call {
	return &Orm_FindOrNew_Call{Call: _e.mock.On("FindOrNew", parent, relation, id, dest)}
}

func (_c *Orm_FindOrNew_Call) Run(run func(parent interface{}, relation string, id interface{}, dest interface{})) *Orm_FindOrNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}), args[3].(interface{}))
	})
	return _c
}

func (_c *Orm_FindOrNew_Call) Return(_a0 error) *Orm_FindOrNew_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_FindOrNew_Call) RunAndReturn(run func(interface{}, string, interface{}, interface{}) error) *Orm_FindOrNew_Call {
	_c.Call.Return(run)
	return _c
}

// FirstOrCreate provides a mock function with given fields: parent, relation, attrs, values, dest
func (_m *Orm) FirstOrCreate(parent interface{}, relation string, attrs map[string]interface{}, values map[string]interface{}, dest interface{}) error {
	ret := _m.Called(parent, relation, attrs, values, dest)

	if len(ret) == 0 {
		panic("no return value specified for FirstOrCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, map[string]interface{}, map[string]interface{}, interface{}) error); ok {
		r0 = rf(parent, relation, attrs, values, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_FirstOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrCreate'
type Orm_FirstOrCreate_Call struct {
	*mock.Call
}

// FirstOrCreate is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - attrs map[string]interface{}
//   - values map[string]interface{}
//   - dest interface{}
func (_e *Orm_Expecter) FirstOrCreate(parent interface{}, relation interface{}, attrs interface{}, values interface{}, dest interface{}) *Orm_FirstOrCreate_Call {
	return &Orm_FirstOrCreate_Call{Call: _e.mock.On("FirstOrCreate", parent, relation, attrs, values, dest)}
}

func (_c *Orm_FirstOrCreate_Call) Run(run func(parent interface{}, relation string, attrs map[string]interface{}, values map[string]interface{}, dest interface{})) *Orm_FirstOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(map[string]interface{}), args[3].(map[string]interface{}), args[4].(interface{}))
	})
	return _c
}

func (_c *Orm_FirstOrCreate_Call) Return(_a0 error) *Orm_FirstOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_FirstOrCreate_Call) RunAndReturn(run func(interface{}, string, map[string]interface{}, map[string]interface{}, interface{}) error) *Orm_FirstOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// FirstOrNew provides a mock function with given fields: parent, relation, attrs, values, dest
func (_m *Orm) FirstOrNew(parent interface{}, relation string, attrs map[string]interface{}, values map[string]interface{}, dest interface{}) error {
	ret := _m.Called(parent, relation, attrs, values, dest)

	if len(ret) == 0 {
		panic("no return value specified for FirstOrNew")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, map[string]interface{}, map[string]interface{}, interface{}) error); ok {
		r0 = rf(parent, relation, attrs, values, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_FirstOrNew_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FirstOrNew'
type Orm_FirstOrNew_Call struct {
	*mock.Call
}

// FirstOrNew is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - attrs map[string]interface{}
//   - values map[string]interface{}
//   - dest interface{}
func (_e *Orm_Expecter) FirstOrNew(parent interface{}, relation interface{}, attrs interface{}, values interface{}, dest interface{}) *Orm_FirstOrNew_Call {
	return &Orm_FirstOrNew_Call{Call: _e.mock.On("FirstOrNew", parent, relation, attrs, values, dest)}
}

func (_c *Orm_FirstOrNew_Call) Run(run func(parent interface{}, relation string, attrs map[string]interface{}, values map[string]interface{}, dest interface{})) *Orm_FirstOrNew_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(map[string]interface{}), args[3].(map[string]interface{}), args[4].(interface{}))
	})
	return _c
}

func (_c *Orm_FirstOrNew_Call) Return(_a0 error) *Orm_FirstOrNew_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_FirstOrNew_Call) RunAndReturn(run func(interface{}, string, map[string]interface{}, map[string]interface{}, interface{}) error) *Orm_FirstOrNew_Call {
	_c.Call.Return(run)
	return _c
}

// Fresh provides a mock function with no fields
func (_m *Orm) Fresh() {
	_m.Called()
}

// Orm_Fresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fresh'
type Orm_Fresh_Call struct {
	*mock.Call
}

// Fresh is a helper method to define mock.On call
func (_e *Orm_Expecter) Fresh() *Orm_Fresh_Call {
	return &Orm_Fresh_Call{Call: _e.mock.On("Fresh")}
}

func (_c *Orm_Fresh_Call) Run(run func()) *Orm_Fresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Orm_Fresh_Call) Return() *Orm_Fresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *Orm_Fresh_Call) RunAndReturn(run func()) *Orm_Fresh_Call {
	_c.Run(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Orm) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Orm_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Orm_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Orm_Expecter) Name() *Orm_Name_Call {
	return &Orm_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Orm_Name_Call) Run(run func()) *Orm_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Orm_Name_Call) Return(_a0 string) *Orm_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Name_Call) RunAndReturn(run func() string) *Orm_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewRelation provides a mock function with given fields: parent, relation
func (_m *Orm) NewRelation(parent interface{}, relation string) orm.Query {
	ret := _m.Called(parent, relation)

	if len(ret) == 0 {
		panic("no return value specified for NewRelation")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func(interface{}, string) orm.Query); ok {
		r0 = rf(parent, relation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// Orm_NewRelation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRelation'
type Orm_NewRelation_Call struct {
	*mock.Call
}

// NewRelation is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
func (_e *Orm_Expecter) NewRelation(parent interface{}, relation interface{}) *Orm_NewRelation_Call {
	return &Orm_NewRelation_Call{Call: _e.mock.On("NewRelation", parent, relation)}
}

func (_c *Orm_NewRelation_Call) Run(run func(parent interface{}, relation string)) *Orm_NewRelation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string))
	})
	return _c
}

func (_c *Orm_NewRelation_Call) Return(_a0 orm.Query) *Orm_NewRelation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_NewRelation_Call) RunAndReturn(run func(interface{}, string) orm.Query) *Orm_NewRelation_Call {
	_c.Call.Return(run)
	return _c
}

// Observe provides a mock function with given fields: model, observer
func (_m *Orm) Observe(model interface{}, observer orm.Observer) {
	_m.Called(model, observer)
}

// Orm_Observe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Observe'
type Orm_Observe_Call struct {
	*mock.Call
}

// Observe is a helper method to define mock.On call
//   - model interface{}
//   - observer orm.Observer
func (_e *Orm_Expecter) Observe(model interface{}, observer interface{}) *Orm_Observe_Call {
	return &Orm_Observe_Call{Call: _e.mock.On("Observe", model, observer)}
}

func (_c *Orm_Observe_Call) Run(run func(model interface{}, observer orm.Observer)) *Orm_Observe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(orm.Observer))
	})
	return _c
}

func (_c *Orm_Observe_Call) Return() *Orm_Observe_Call {
	_c.Call.Return()
	return _c
}

func (_c *Orm_Observe_Call) RunAndReturn(run func(interface{}, orm.Observer)) *Orm_Observe_Call {
	_c.Run(run)
	return _c
}

// Query provides a mock function with no fields
func (_m *Orm) Query() orm.Query {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 orm.Query
	if rf, ok := ret.Get(0).(func() orm.Query); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Query)
		}
	}

	return r0
}

// Orm_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Orm_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
func (_e *Orm_Expecter) Query() *Orm_Query_Call {
	return &Orm_Query_Call{Call: _e.mock.On("Query")}
}

func (_c *Orm_Query_Call) Run(run func()) *Orm_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Orm_Query_Call) Return(_a0 orm.Query) *Orm_Query_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Query_Call) RunAndReturn(run func() orm.Query) *Orm_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: parent, relation, child
func (_m *Orm) Save(parent interface{}, relation string, child interface{}) error {
	ret := _m.Called(parent, relation, child)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}) error); ok {
		r0 = rf(parent, relation, child)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type Orm_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - child interface{}
func (_e *Orm_Expecter) Save(parent interface{}, relation interface{}, child interface{}) *Orm_Save_Call {
	return &Orm_Save_Call{Call: _e.mock.On("Save", parent, relation, child)}
}

func (_c *Orm_Save_Call) Run(run func(parent interface{}, relation string, child interface{})) *Orm_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Orm_Save_Call) Return(_a0 error) *Orm_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Save_Call) RunAndReturn(run func(interface{}, string, interface{}) error) *Orm_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveMany provides a mock function with given fields: parent, relation, children
func (_m *Orm) SaveMany(parent interface{}, relation string, children interface{}) error {
	ret := _m.Called(parent, relation, children)

	if len(ret) == 0 {
		panic("no return value specified for SaveMany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}) error); ok {
		r0 = rf(parent, relation, children)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_SaveMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveMany'
type Orm_SaveMany_Call struct {
	*mock.Call
}

// SaveMany is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - children interface{}
func (_e *Orm_Expecter) SaveMany(parent interface{}, relation interface{}, children interface{}) *Orm_SaveMany_Call {
	return &Orm_SaveMany_Call{Call: _e.mock.On("SaveMany", parent, relation, children)}
}

func (_c *Orm_SaveMany_Call) Run(run func(parent interface{}, relation string, children interface{})) *Orm_SaveMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *Orm_SaveMany_Call) Return(_a0 error) *Orm_SaveMany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_SaveMany_Call) RunAndReturn(run func(interface{}, string, interface{}) error) *Orm_SaveMany_Call {
	_c.Call.Return(run)
	return _c
}

// SaveManyWithPivot provides a mock function with given fields: parent, relation, children, attrsPerChild
func (_m *Orm) SaveManyWithPivot(parent interface{}, relation string, children interface{}, attrsPerChild map[interface{}]map[string]interface{}) error {
	ret := _m.Called(parent, relation, children, attrsPerChild)

	if len(ret) == 0 {
		panic("no return value specified for SaveManyWithPivot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}, map[interface{}]map[string]interface{}) error); ok {
		r0 = rf(parent, relation, children, attrsPerChild)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_SaveManyWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveManyWithPivot'
type Orm_SaveManyWithPivot_Call struct {
	*mock.Call
}

// SaveManyWithPivot is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - children interface{}
//   - attrsPerChild map[interface{}]map[string]interface{}
func (_e *Orm_Expecter) SaveManyWithPivot(parent interface{}, relation interface{}, children interface{}, attrsPerChild interface{}) *Orm_SaveManyWithPivot_Call {
	return &Orm_SaveManyWithPivot_Call{Call: _e.mock.On("SaveManyWithPivot", parent, relation, children, attrsPerChild)}
}

func (_c *Orm_SaveManyWithPivot_Call) Run(run func(parent interface{}, relation string, children interface{}, attrsPerChild map[interface{}]map[string]interface{})) *Orm_SaveManyWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}), args[3].(map[interface{}]map[string]interface{}))
	})
	return _c
}

func (_c *Orm_SaveManyWithPivot_Call) Return(_a0 error) *Orm_SaveManyWithPivot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_SaveManyWithPivot_Call) RunAndReturn(run func(interface{}, string, interface{}, map[interface{}]map[string]interface{}) error) *Orm_SaveManyWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWithPivot provides a mock function with given fields: parent, relation, child, attrs
func (_m *Orm) SaveWithPivot(parent interface{}, relation string, child interface{}, attrs map[string]interface{}) error {
	ret := _m.Called(parent, relation, child, attrs)

	if len(ret) == 0 {
		panic("no return value specified for SaveWithPivot")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}, map[string]interface{}) error); ok {
		r0 = rf(parent, relation, child, attrs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_SaveWithPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWithPivot'
type Orm_SaveWithPivot_Call struct {
	*mock.Call
}

// SaveWithPivot is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - child interface{}
//   - attrs map[string]interface{}
func (_e *Orm_Expecter) SaveWithPivot(parent interface{}, relation interface{}, child interface{}, attrs interface{}) *Orm_SaveWithPivot_Call {
	return &Orm_SaveWithPivot_Call{Call: _e.mock.On("SaveWithPivot", parent, relation, child, attrs)}
}

func (_c *Orm_SaveWithPivot_Call) Run(run func(parent interface{}, relation string, child interface{}, attrs map[string]interface{})) *Orm_SaveWithPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *Orm_SaveWithPivot_Call) Return(_a0 error) *Orm_SaveWithPivot_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_SaveWithPivot_Call) RunAndReturn(run func(interface{}, string, interface{}, map[string]interface{}) error) *Orm_SaveWithPivot_Call {
	_c.Call.Return(run)
	return _c
}

// SetQuery provides a mock function with given fields: query
func (_m *Orm) SetQuery(query orm.Query) {
	_m.Called(query)
}

// Orm_SetQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetQuery'
type Orm_SetQuery_Call struct {
	*mock.Call
}

// SetQuery is a helper method to define mock.On call
//   - query orm.Query
func (_e *Orm_Expecter) SetQuery(query interface{}) *Orm_SetQuery_Call {
	return &Orm_SetQuery_Call{Call: _e.mock.On("SetQuery", query)}
}

func (_c *Orm_SetQuery_Call) Run(run func(query orm.Query)) *Orm_SetQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(orm.Query))
	})
	return _c
}

func (_c *Orm_SetQuery_Call) Return() *Orm_SetQuery_Call {
	_c.Call.Return()
	return _c
}

func (_c *Orm_SetQuery_Call) RunAndReturn(run func(orm.Query)) *Orm_SetQuery_Call {
	_c.Run(run)
	return _c
}

// Sync provides a mock function with given fields: parent, relation, ids
func (_m *Orm) Sync(parent interface{}, relation string, ids []interface{}) (*db.SyncResult, error) {
	ret := _m.Called(parent, relation, ids)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, string, []interface{}) (*db.SyncResult, error)); ok {
		return rf(parent, relation, ids)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, []interface{}) *db.SyncResult); ok {
		r0 = rf(parent, relation, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, []interface{}) error); ok {
		r1 = rf(parent, relation, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orm_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type Orm_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - ids []interface{}
func (_e *Orm_Expecter) Sync(parent interface{}, relation interface{}, ids interface{}) *Orm_Sync_Call {
	return &Orm_Sync_Call{Call: _e.mock.On("Sync", parent, relation, ids)}
}

func (_c *Orm_Sync_Call) Run(run func(parent interface{}, relation string, ids []interface{})) *Orm_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].([]interface{}))
	})
	return _c
}

func (_c *Orm_Sync_Call) Return(_a0 *db.SyncResult, _a1 error) *Orm_Sync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orm_Sync_Call) RunAndReturn(run func(interface{}, string, []interface{}) (*db.SyncResult, error)) *Orm_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// SyncWithoutDetaching provides a mock function with given fields: parent, relation, ids
func (_m *Orm) SyncWithoutDetaching(parent interface{}, relation string, ids []interface{}) (*db.SyncResult, error) {
	ret := _m.Called(parent, relation, ids)

	if len(ret) == 0 {
		panic("no return value specified for SyncWithoutDetaching")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, string, []interface{}) (*db.SyncResult, error)); ok {
		return rf(parent, relation, ids)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, []interface{}) *db.SyncResult); ok {
		r0 = rf(parent, relation, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, []interface{}) error); ok {
		r1 = rf(parent, relation, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orm_SyncWithoutDetaching_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncWithoutDetaching'
type Orm_SyncWithoutDetaching_Call struct {
	*mock.Call
}

// SyncWithoutDetaching is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - ids []interface{}
func (_e *Orm_Expecter) SyncWithoutDetaching(parent interface{}, relation interface{}, ids interface{}) *Orm_SyncWithoutDetaching_Call {
	return &Orm_SyncWithoutDetaching_Call{Call: _e.mock.On("SyncWithoutDetaching", parent, relation, ids)}
}

func (_c *Orm_SyncWithoutDetaching_Call) Run(run func(parent interface{}, relation string, ids []interface{})) *Orm_SyncWithoutDetaching_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].([]interface{}))
	})
	return _c
}

func (_c *Orm_SyncWithoutDetaching_Call) Return(_a0 *db.SyncResult, _a1 error) *Orm_SyncWithoutDetaching_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orm_SyncWithoutDetaching_Call) RunAndReturn(run func(interface{}, string, []interface{}) (*db.SyncResult, error)) *Orm_SyncWithoutDetaching_Call {
	_c.Call.Return(run)
	return _c
}

// Toggle provides a mock function with given fields: parent, relation, ids
func (_m *Orm) Toggle(parent interface{}, relation string, ids []interface{}) (*db.SyncResult, error) {
	ret := _m.Called(parent, relation, ids)

	if len(ret) == 0 {
		panic("no return value specified for Toggle")
	}

	var r0 *db.SyncResult
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, string, []interface{}) (*db.SyncResult, error)); ok {
		return rf(parent, relation, ids)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, []interface{}) *db.SyncResult); ok {
		r0 = rf(parent, relation, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.SyncResult)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, []interface{}) error); ok {
		r1 = rf(parent, relation, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orm_Toggle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Toggle'
type Orm_Toggle_Call struct {
	*mock.Call
}

// Toggle is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - ids []interface{}
func (_e *Orm_Expecter) Toggle(parent interface{}, relation interface{}, ids interface{}) *Orm_Toggle_Call {
	return &Orm_Toggle_Call{Call: _e.mock.On("Toggle", parent, relation, ids)}
}

func (_c *Orm_Toggle_Call) Run(run func(parent interface{}, relation string, ids []interface{})) *Orm_Toggle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].([]interface{}))
	})
	return _c
}

func (_c *Orm_Toggle_Call) Return(_a0 *db.SyncResult, _a1 error) *Orm_Toggle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orm_Toggle_Call) RunAndReturn(run func(interface{}, string, []interface{}) (*db.SyncResult, error)) *Orm_Toggle_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: txFunc
func (_m *Orm) Transaction(txFunc func(orm.Query) error) error {
	ret := _m.Called(txFunc)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(func(orm.Query) error) error); ok {
		r0 = rf(txFunc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type Orm_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - txFunc func(orm.Query) error
func (_e *Orm_Expecter) Transaction(txFunc interface{}) *Orm_Transaction_Call {
	return &Orm_Transaction_Call{Call: _e.mock.On("Transaction", txFunc)}
}

func (_c *Orm_Transaction_Call) Run(run func(txFunc func(orm.Query) error)) *Orm_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(orm.Query) error))
	})
	return _c
}

func (_c *Orm_Transaction_Call) Return(_a0 error) *Orm_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_Transaction_Call) RunAndReturn(run func(func(orm.Query) error) error) *Orm_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExistingPivot provides a mock function with given fields: parent, relation, id, attrs
func (_m *Orm) UpdateExistingPivot(parent interface{}, relation string, id interface{}, attrs map[string]interface{}) (int64, error) {
	ret := _m.Called(parent, relation, id, attrs)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExistingPivot")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}, map[string]interface{}) (int64, error)); ok {
		return rf(parent, relation, id, attrs)
	}
	if rf, ok := ret.Get(0).(func(interface{}, string, interface{}, map[string]interface{}) int64); ok {
		r0 = rf(parent, relation, id, attrs)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(interface{}, string, interface{}, map[string]interface{}) error); ok {
		r1 = rf(parent, relation, id, attrs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Orm_UpdateExistingPivot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExistingPivot'
type Orm_UpdateExistingPivot_Call struct {
	*mock.Call
}

// UpdateExistingPivot is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - id interface{}
//   - attrs map[string]interface{}
func (_e *Orm_Expecter) UpdateExistingPivot(parent interface{}, relation interface{}, id interface{}, attrs interface{}) *Orm_UpdateExistingPivot_Call {
	return &Orm_UpdateExistingPivot_Call{Call: _e.mock.On("UpdateExistingPivot", parent, relation, id, attrs)}
}

func (_c *Orm_UpdateExistingPivot_Call) Run(run func(parent interface{}, relation string, id interface{}, attrs map[string]interface{})) *Orm_UpdateExistingPivot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(interface{}), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *Orm_UpdateExistingPivot_Call) Return(_a0 int64, _a1 error) *Orm_UpdateExistingPivot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Orm_UpdateExistingPivot_Call) RunAndReturn(run func(interface{}, string, interface{}, map[string]interface{}) (int64, error)) *Orm_UpdateExistingPivot_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrCreate provides a mock function with given fields: parent, relation, attrs, values, dest
func (_m *Orm) UpdateOrCreate(parent interface{}, relation string, attrs map[string]interface{}, values map[string]interface{}, dest interface{}) error {
	ret := _m.Called(parent, relation, attrs, values, dest)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, string, map[string]interface{}, map[string]interface{}, interface{}) error); ok {
		r0 = rf(parent, relation, attrs, values, dest)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Orm_UpdateOrCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrCreate'
type Orm_UpdateOrCreate_Call struct {
	*mock.Call
}

// UpdateOrCreate is a helper method to define mock.On call
//   - parent interface{}
//   - relation string
//   - attrs map[string]interface{}
//   - values map[string]interface{}
//   - dest interface{}
func (_e *Orm_Expecter) UpdateOrCreate(parent interface{}, relation interface{}, attrs interface{}, values interface{}, dest interface{}) *Orm_UpdateOrCreate_Call {
	return &Orm_UpdateOrCreate_Call{Call: _e.mock.On("UpdateOrCreate", parent, relation, attrs, values, dest)}
}

func (_c *Orm_UpdateOrCreate_Call) Run(run func(parent interface{}, relation string, attrs map[string]interface{}, values map[string]interface{}, dest interface{})) *Orm_UpdateOrCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}), args[1].(string), args[2].(map[string]interface{}), args[3].(map[string]interface{}), args[4].(interface{}))
	})
	return _c
}

func (_c *Orm_UpdateOrCreate_Call) Return(_a0 error) *Orm_UpdateOrCreate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_UpdateOrCreate_Call) RunAndReturn(run func(interface{}, string, map[string]interface{}, map[string]interface{}, interface{}) error) *Orm_UpdateOrCreate_Call {
	_c.Call.Return(run)
	return _c
}

// WithContext provides a mock function with given fields: ctx
func (_m *Orm) WithContext(ctx context.Context) orm.Orm {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for WithContext")
	}

	var r0 orm.Orm
	if rf, ok := ret.Get(0).(func(context.Context) orm.Orm); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(orm.Orm)
		}
	}

	return r0
}

// Orm_WithContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithContext'
type Orm_WithContext_Call struct {
	*mock.Call
}

// WithContext is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Orm_Expecter) WithContext(ctx interface{}) *Orm_WithContext_Call {
	return &Orm_WithContext_Call{Call: _e.mock.On("WithContext", ctx)}
}

func (_c *Orm_WithContext_Call) Run(run func(ctx context.Context)) *Orm_WithContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Orm_WithContext_Call) Return(_a0 orm.Orm) *Orm_WithContext_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Orm_WithContext_Call) RunAndReturn(run func(context.Context) orm.Orm) *Orm_WithContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrm creates a new instance of Orm. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrm(t interface {
	mock.TestingT
	Cleanup(func())
}) *Orm {
	mock := &Orm{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
